export const ADD_PACKET_PENDING = 'ADD_PACKET_PENDING'
export const ADD_PACKET_SUCCESS = 'ADD_PACKET_SUCCESS'
export const ADD_PACKET_FAILURE = 'ADD_PACKET_FAILURE'
export const CLEAR_ERROR = 'CLEAR_ERROR'
